-- Supabase PostgreSQL Schema for TOOTH FAIRY

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table: user_profiles
-- Stores roles for RBAC (Role-Based Access Control)
CREATE TABLE user_profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('patient', 'staff')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table: triage_scans
-- Stores AI analysis results from patient intraoral scans.
CREATE TABLE triage_scans (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    findings JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending_review' CHECK (status IN ('pending_review', 'reviewed', 'actioned')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table: odontogram_charts
-- Stores the clinical findings generated by the Voice-to-Odontogram AI.
CREATE TABLE odontogram_charts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    staff_id UUID NOT NULL REFERENCES auth.users(id),
    chart_data JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- RLS (Row Level Security) Configuration
-- ==========================================

ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE triage_scans ENABLE ROW LEVEL SECURITY;
ALTER TABLE odontogram_charts ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------
-- Policies for user_profiles
-- ------------------------------------------
-- Users can view their own profile
CREATE POLICY "Users view own profile" 
ON user_profiles FOR SELECT 
USING (auth.uid() = id);

-- ------------------------------------------
-- Policies for triage_scans
-- ------------------------------------------
-- Patients can INSERT their own scans
CREATE POLICY "Patients insert own scans"
ON triage_scans FOR INSERT
WITH CHECK (auth.uid() = patient_id);

-- Patients can SELECT their own scans
CREATE POLICY "Patients view own scans"
ON triage_scans FOR SELECT
USING (auth.uid() = patient_id);

-- Staff can view all scans
CREATE POLICY "Staff view all scans"
ON triage_scans FOR SELECT
USING (
    EXISTS (SELECT 1 FROM user_profiles WHERE id = auth.uid() AND role = 'staff')
);

-- Staff can UPDATE scans to 'reviewed'
CREATE POLICY "Staff update scans"
ON triage_scans FOR UPDATE
USING (
    EXISTS (SELECT 1 FROM user_profiles WHERE id = auth.uid() AND role = 'staff')
);

-- ------------------------------------------
-- Policies for odontogram_charts
-- ------------------------------------------
-- Staff can INSERT odontogram charts
CREATE POLICY "Staff insert charts"
ON odontogram_charts FOR INSERT
WITH CHECK (
    EXISTS (SELECT 1 FROM user_profiles WHERE id = auth.uid() AND role = 'staff')
);

-- Staff can SELECT all odontogram charts
CREATE POLICY "Staff view all charts"
ON odontogram_charts FOR SELECT
USING (
    EXISTS (SELECT 1 FROM user_profiles WHERE id = auth.uid() AND role = 'staff')
);

-- Patients can SELECT their own odontogram charts
CREATE POLICY "Patients view own charts"
ON odontogram_charts FOR SELECT
USING (auth.uid() = patient_id);
